echo "<<<<<<<<<<<<<<<<<<<<<<conector mongodb Test17_A >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
curl -X PUT 'http://localhost:8083/connectors/ZPFM.PFM.CGE.Test17_A/config' -H 'Content-Type: application/json' --data '
{
   "connector.class": "com.mongodb.kafka.connect.MongoSinkConnector",
    "tasks.max": "6",
    "topics": "ZPFM.PFM.CGE.Test17_A",
    "connection.uri":"mongodb+srv://user:pass@cluster0.vttd8.mongodb.net/?retryWrites=true&w=majority",
    "database":"ZPFMMDB001_CGD",
    "collection": "movimientosCuenta",
    "writemodel.strategy": "com.mongodb.kafka.connect.sink.writemodel.strategy.UpdateOneBusinessKeyTimestampStrategy",
    "document.id.strategy": "com.mongodb.kafka.connect.sink.processor.id.strategy.PartialValueStrategy",
    "post.processor.chain": "com.mongodb.kafka.connect.sink.processor.DocumentIdAdder",
    "document.id.strategy.overwrite.existing": "true",
    "document.id.strategy.partial.value.projection.type": "allowlist",
    "document.id.strategy.partial.value.projection.list": "fecha, _id",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.converter.schemas.enable": false,
    "errors.tolerance": "all",
    "errors.log.include.messages": true,
    "errors.deadletterqueue.context.headers.enable": true,
    "errors.log.enable": true,
    "errors.deadletterqueue.topic.name": "ZPFM.MONGO.CGE.DLQ_Test17_A",
    "errors.deadletterqueue.topic.replication.factor": 1,
    "max.num.retries": 50,
    "retries.defer.timeout": 500,
    "transforms": "WrapKey, RenameField",
    "transforms.WrapKey.type": "org.apache.kafka.connect.transforms.HoistField$Key",
    "transforms.WrapKey.field": "referencia",
    "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
    "transforms.RenameField.renames": "movimientoId:_id"
}' -w   "\n"
echo "<<<<<<<<<<<<<<<<<<<<<conector mongodb Test17_B>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
curl -X PUT 'http://localhost:8083/connectors/ZPFM.PFM.CGE.Test17_B/config' -H 'Content-Type: application/json' --data '
{
    "connector.class": "com.mongodb.kafka.connect.MongoSinkConnector",
    "tasks.max": "6",
    "topics": "ZPFM.PFM.CGE.Test17_B",
    "connection.uri":"mongodb+srv://user:pass@cluster0.vttd8.mongodb.net/?retryWrites=true&w=majority",
    "database":"ZPFMMDB001_CGD",
    "collection": "movimientosCuenta",
    "writemodel.strategy": "com.mongodb.kafka.connect.sink.writemodel.strategy.UpdateOneBusinessKeyTimestampStrategy",
    "document.id.strategy": "com.mongodb.kafka.connect.sink.processor.id.strategy.PartialValueStrategy",
    "post.processor.chain": "com.mongodb.kafka.connect.sink.processor.DocumentIdAdder",
    "document.id.strategy.overwrite.existing": "true",
    "document.id.strategy.partial.value.projection.type": "allowlist",
    "document.id.strategy.partial.value.projection.list": "fecha, _id",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.converter.schemas.enable": false,
    "errors.tolerance": "all",
    "errors.log.include.messages": true,
    "errors.deadletterqueue.context.headers.enable": true,
    "errors.log.enable": true,
    "errors.deadletterqueue.topic.name": "ZPFM.MONGO.CGE.DLQ_Test17_B",
    "errors.deadletterqueue.topic.replication.factor": 1,
    "max.num.retries": 50,
    "retries.defer.timeout": 500,
    "transforms": "WrapKey, RenameField",
    "transforms.WrapKey.type": "org.apache.kafka.connect.transforms.HoistField$Key",
    "transforms.WrapKey.field": "referencia",
    "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
    "transforms.RenameField.renames": "movimientoId:_id"
}' -w  "\n"
